### ISSUE TITLE
ECIP-1070: ProgPoW for ETC Discussions

### ISSUE THREAD

**Issue by YazzyYaz** [ethereumclassic/ECIPs#172]
Discussions for ProgPoW for ETC Discussions concerning this Pull Request: https://github.com/ethereumclassic/ECIPs/pull/171

**Comment by realcodywburns** [comment]
Conclusion of hardware and software security audits.
https://medium.com/ethereum-cat-herders/progpow-audits-released-ed4973ebe073

**Comment by realcodywburns** [comment]
**Former home of gangnum testnet**. https://github.com/greerso/testnet
Status Dashboard: http://boot.gangnam.ethdevops.io/
Block Explorer: https://gangnam.etherchain.org/
Mining Pool: https://gangnam.wattpool.net/
Gitter Support: https://gitter.im/ifdefelse/community/

**Comment by realcodywburns** [comment]
Current Trello of ProgPoW hype/fud https://trello.com/b/KrD25QI5/progpow

**Comment by BelfordZ** [comment]
gonna post the same comment I wrote for the sha3 ticket:
![image](https://user-images.githubusercontent.com/1787231/68448641-01338880-0199-11ea-8f48-613aa7631570.png)

**Comment by zmitton** [comment]
The asymmetry between mining and verifying is still problematic (too low). It has the same issue as Ethash: Extremely expensive verification (compared to sha256, for instance). This is because of a pseudo-random changing of params per epoch (every ~5 days). This prevents the ability to have a   [pure function](https://en.wikipedia.org/wiki/Pure_function) for verification. It requires a much more expensive _context_: The full historic datasets that resulted in particular epoch params.

**Comment by soc1c** [comment]
Yeah, that's why I believe SHA3 is the most elegant solution.

**Comment by GregTheGreek** [comment]
I believe this can be closed.
