### ISSUE TITLE
Core Devs Call: ECIP-1061 Aztlán Upgrade

### ISSUE THREAD

**Issue by soc1c** [ethereumclassic/ECIPs#177]
Ref [ECIP-1061](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1061.md) #81 #157 #176 

### ETC Core Devs Call - Aztlán Finalization

When: **Wednesday, November 27, 2019, 1pm UTC**, 60 minutes max.

Where: **Ethereum Classic Discord** https://discord.gg/dwxb6nf `#ecips` channel. Will use/create a voice channel _ad hoc._

### Agenda

- Quick client teams check-in
  - Parity Ethereum / Parity Tech
  - Geth Classic / ChainSafe, ETCLabs Core
  - Multi-Geth / Multi-Geth, ETCLabs Core 
  - Hyperledger Besu / ChainSafe, PegaSys
- Aztlán (ECIP-1061) needs to be either **accepted** or _updated_ (or _rejected_)
  - discuss included EIPs
  - discuss a timeline for the protocol upgrade
    - Mordor Classic and Kotti Classic testnet (February?)
    - Ethereum Classic mainnet (March?)
- anything else related to Aztlán

Please comment to add items to the agenda

**Comment by bobsummerwill** [comment]
ETCLabs Core -> ETC Core :-)

**Comment by bobsummerwill** [comment]
Please can I suggest that we move the timelines up on the Aztlán Upgrade meeting, @soc1c?

Core Devs Call: Mining Algorithm Upgrade
Nov 21st is fine, I think.  Two weeks time.

Core Devs Call: ECIP-1061 Aztlán Upgrade
I suggest that we move this to Nov 28th, because we can be starting to talk about this before Agharta is finalized.  Versus Dec 19th as currently planned.   The main critical path here will NOT be technical, but gathering social consensus, so having this 3 weeks earlier would be very helpful.   Also, by Dec 19th a number of people will be having Christmas plans.

Core Devs Call: ECIP-1056 Agharta Finalization
Dec 5th

**Comment by bobsummerwill** [comment]
It has been pointed out that Nov 28th is US Thanksgiving, so maybe Dec 12th instead?

**Comment by soc1c** [comment]
Moved to 11/27 (Wednesday!) to avoid Thanksgiving and start talking about Aztlan early.

**Comment by soc1c** [comment]
### Attendees
- bobsummerwill
- Classic_Kevin_IOHK
- DontPanicBurns
- GregTheGreek
- husainfazel
- soc1c
- sorpaas
- Tj
- tzdybal
- wolf_li
- yaz
- zacmitton

### Call minutes
- Afri: Let's start discussing Aztlan ECIP variants
- Afri: Main difference is inclusion of EIP 1884 - yes or no? any comments?
- Tomek: We don't want to break existing contracts
- Wei: EIP 1884 actually fixes a DoS vector that should be considered
- Wei: If we want to enable we should analyze the ETC blockchain first
- Bob: We should not exclude EIP 1884 as it is an optimization
- Bob: Ideally, we want to do that in a backward-compatible way
- Bob: Safe choice would be Istanbul without EIP 1884, the even better choice is Istanbul with EIP 1884 plus account versioning
- Wei: Proposes account versioning hardfork first
- Tomek: What would be the distance between the two hardforks?
- Wei: Normal hardfork, no minimal distance, maybe a couple of weeks
- Terry: Do you have a recommendation what to do first?
- Zac: Why would contracts break from EIP 1884?
- Bob: Especially the 600 Aragon contracts would break
- Afri: Explicit gas price assumptions written in the contract
- Cody: But that is a programming issue not protocol issue
- Zac: If it's a weird assembly thing, then it's just more unlikely
- Wei: Some weird hack
- Afri: What's the sentiment, with or without EIP 1884?
- Yaz: EIP 1884 should be excluded and come together with account versioning
- Terry: Would you consider account versioning first
- Yaz: Sure
- Afri: Aztlan could be activated easily in 3 months because all clients support it and bundle EIP 1884 with account versioning later
- Bob: EIP 1702 was implemented in all clients already
- Bob: We should stick to 3 months without delay though
- Wei: 1702 has an extension, new version could be implemented easily and in a backward-compatible way
- Wei: We should have account versioning after Istanbul
- Greg: Asks a sleepy question about EIP 1884
- Wei: Answers something
- Greg: "Ooooh" (good morning!)
- Yaz: For Aztlan we can use opportunity to talk about other ECIPs, too
- Tomek: Anyone proposing any ECIP? If not, we shouldn't discuss them
- Bob: No proposals
- Afri: EF network will act as a testnet for Classic with the upcoming Istanbul fork
- Tomek: Best idea would be to have Aztlan without EIP 1884 and then have EIP 1884 with account versioning?
- Wei: Yeah right, we would need a new specification
- Afri: Shall we lock in Aztlan?
- **Rough consensus on Aztlan without EIP 1884 (Yingchun flavor)**
- Afri: Shall we add EIP 1884 plus account versioning in a subsequent hardfork?
- Bob: Maybe new ECIP, doesn't necessarily have to be EIP 1884
- Yaz: Do we need other tooling if we exclude 1884?
- Bob: Not required
- Wei: It's only gas assumptions. The correct answer is "yes" but the differences are only very slight.
- Bob: Differences are slight anyways
- Back and forth between Bob and Wei
- Greg: Doesn't think the gas table affects compiler, we are probably good
- Zac: Why is it in there?
- Afri: Aztlan on mainnet March 2020, testnet in February 2020?
- Yaz: Might break anything, so careful
- Bob: Just be clear, we don't have to maintain any tooling
- Greg also says something
- Afri: Let's move Aztlan to last call? Testnets in February and decided block numbers offline?
- _Silence..._
- Afri: Is this "don't care" or "rough consensus?"
- Cody: _Rough consensus..._
- Wei: Just to be clear? Are we using ECIP 1072? How long should "last call" last?
- Afri: Three weeks "last call" would be sufficient to evaluate Istanbul on EF network
- Everyone: Sounds good
- Afri: Any final comments?
- Bob: Are we calling it Yingchun now?
- Wei: No, let's stick with Aztlan
- Yaz: We already communicated Aztlan
- Afri: Let's call it Yingchun flavored Aztlan (ECIP 1061)
- _Thanks everyone_

**Comment by sorpaas** [comment]
My meeting notes for the last section of the call:

* Wei: Just to make it clear, does this mean we move forward with 1072 to "Last Call" status? If that is the case, how long should be the last call period? Three weeks?
* Afri: Three weeks should be sufficient. We also get to evaluate it on the Ethereum network first.
* [No further comments, assumed everyone agreed.]
* Bob: Since we decide to move forward with 1072, does this mean we will change the hard fork name to Yingchun?
* Wei: No. I'll modify the title of 1072 to make Yingchun the edition name, but since Aztlan was already decided, let's still call it the hard fork name.
* Yaz: [Repeat what Wei has said] The hard fork name is already decided to be Aztlan, so that's what it should be called. I do not object giving it a small "hat" name Yingchun.
* Afri: Okay, then let's call it Aztlan with Yingchun edition.

I do not think Afri's meeting notes on this part is correct.

* It logically does not follow if we are talking about 1072 for the whole section, and then suddenly jumped back to 1061 just for the last sentence.
* It contradicts to Bob's question -- if we were indeed talking about 1061, Bob wouldn't have asked the question whether the hard fork will be named "Yingchun", because when the meeting happened, 1061 does not have that name at all.

**Comment by soc1c** [comment]
Oh, suddenly, 5 days later you have notes? Very creative!

Are we playing this game now after every meeting? On the call we make decisions and afterwards Wei is opening a can of worms to waste everyone's time disputing the consensus we reached on the calls even though you were on these calls?

For the future of humanity, what does it matter if Ethereum Classic specifies a hardfork in 1061 or 1072? Nothing!

I suggest you zoom out a bit and do some reality checks. Maybe spend a day with your girlfriend in the mountains, go hiking, or fishing at the sea and reflect your actions a bit from distance.

I understand that you are hurt because you didn't get to write the specification but that does not allow you to blackmail an entire community by threatening you stopping to support Ethereum Classic in Multi-Geth, removing Sputnik VM from Classic, and even proposing a Classic Classic one-man fork... just over a god damn number!

Let's move on.

**Comment by sorpaas** [comment]
@soc1c I do not see why this issue should be locked, as it doesn't feel heated at all. Well, okay, probably you are..

This thing matters because of the process. If someone can bypass the process today, they may bypass it tomorrow to move forward a DAO-like hard fork on Ethereum Classic. This is the only process we have at this moment. As the author of the currently accepted ECIP process, it's important for me, and for community members, to make sure it is functional.

I find the rest of your post was just... name calling and personal attacks? Anyway, I'll just pretend I didn't see them! :)

**Comment by sorpaas** [comment]
I only wrote the last section of the meeting notes, because that's what I care about. I'll not be the only person to publish the meeting notes. @developerkevin also has meeting notes of this not yet published.

**Comment by soc1c** [comment]
Cool, a week later everyone writes his own notes. That's how history is _made_. Can't wait to _read_ it.

**Comment by bobsummerwill** [comment]
@sorpaas AGAIN you are trying to use my words in support of your interpretation.

When I said "Should we change the hard fork name to Yingchun?" I was NOT "jumping between ECIPs", because 1061 (updated) and 1072 had become the same.

I really did not care whether we "adopt 1072" or "update 1061" because the outcome was identical.

We had come to HUMAN CONSENSUS within the meeting that the scope of Aztlan was "Istanbul - 1884".    Whether that happened via 1061 or 1072 is utterly unimportant.

Afri's actions reflected what was agreed in the meeting.

You may think you are fighting some holy war here which is protecting the sanctity of the ECIP-1000 process, but that is not what you are actually doing.    What you are actually doing is creating a hugely frustrating and unnecessary "civil war" within ETC, but with only you on the "1072 side" of it.

You have called me malicious in the very recent past.    You have called Afri malicious.   You have threatened the ETC ecosystem that you will not support "ETC 1061" in SputnikVM or MultiGeth.   You have threatened to create Ethereum Classic Classic.

Even yesterday and today you continue to fight and fight and waste more time.

Please for the love of God step away from the keyboard for a day or two.    You are destroying all of the huge credibility and good karma you had built up within ETC.

**Comment by sorpaas** [comment]
@bobsummerwill Well, since you have repeatedly brought this up, let's continue this. Again, I'll ignore your personal attack part. I believe readers can judge it themselves.

We have human consensus to move forward with 1072, as said above. No matter how you want to interpret it now, you have said those words in the meeting, and things do not follow logic if the decision was to move forward with 1061, based on plain words, as explained above. You have failed to provide any justifications or explanations.

It's also not only me on the "1072 side". Multiple community members, if you care about to read the Discord channel, have voiced that the decision was to move forward with 1072. It's rather that just you, Afri, and Yaz said otherwise, had been pretty load (for what purpose, exactly?), and even had to use dirty tricks to discredit me. Most people who are on the "1072 side" do not want to make a fuss about it, because the specifications will be technically the same. I'm on that group as well, as I do not object moving forward with 1061 lately. However, I will not tolerate you, Afri and Yaz continuing to spread false information saying that the decision reached was 1061.

**Comment by bobsummerwill** [comment]
We agreed on THE SCOPE which was Istanbul - 1884.

1072 captured that scope.
Afri updated 1061 to reflect that scope too, adding you as an author too.
You later pointed out licensing issue.  That was addressed yesterday (#216).

Everyone is in consensus on the content.

If Afri "breached process" here is was in some tiny way which really does not matter.   If we need to update ECIP-1000 to ensure that does not happen again then we will.

#221 from @shanejonas and #224 from @meowsbits are seeking to do exactly that.

You on the other hand are throwing around "malicious" and creating days and day worth of drama over nothing.   The whole ecosystem agreed on that scope - yourself included.

Even your threats of breaking away with 1072 would have actually been IDENTICAL protocol.  Literally exactly the same.   "1016 clients" and "1072 clients" would have been the same.

You have generated days and days of wasted effort and drama over the tiniest little breach of process, and even that "breach" is pretty subjective.

**Comment by sorpaas** [comment]
@bobsummerwill We not only agreed on the scope, but also, we agreed on the ECIP to move forward in the meeting. This can be proved in the meeting notes that I explicitly asked whether the the specification we will move forward is ECIP-1072:

> Wei: Just to make it clear, does this mean we move forward with 1072 to "Last Call" status? If that is the case, how long should be the last call period? Three weeks?

Now. I do not know why you want to bring up all those controversy again. You can read Discord chat history to know that the above is a fact independently acknowledged by multiple community members.

**Comment by phyro** [comment]
> This thing matters because of the process. If someone can bypass the process today, they may bypass it tomorrow to move forward a DAO-like hard fork on Ethereum Classic. This is the only process we have at this moment.

This. Always follow the process or open an attack vector. Yes, even if it's us, the good guys and it will slow us down a bit. This specific case is a bit unfortunate because it makes it seem unimportant, but precision matters in the long run because you can't be exact on one ECIP and less exact on the other. It opens up the same issue that the DAO HF did e.g. who decides when things are important? It's literally the same pandora's box opening as the DAO but in a different setting.

**Comment by bobsummerwill** [comment]
Having precise process which we follow is very important, yes, @phyro.
I do not disagree.

**Comment by drd34d** [comment]
Call consensus, as noted, was 1072 not "1061 after being edited". @sorpaas thank you for standing your ground against another attempt to "run the show".

**Comment by YazzyYaz** [comment]
@drd34d you weren't even on the call and it wasn't recorded, so not sure what you're doing other than trying to add fuel to the fire for your own amusement. 

It is amusing you are certain we are talking about 1072 only on an issue ticket about ECIP-1061 call.

**Comment by sorpaas** [comment]
@YazzyYaz I think @drd34d is rather making his only conclusions as an outsider, after reading all the arguments above about what has happened. So far, I've only seen logical inconsistency from the side still arguing "1061 after being edited". If you want to find attestations from people who attended the call to confirm that the call consensus was indeed 1072, look for Discord chat history.

As the content of the call is indeed about 1061/1702, let me modify the issue title to reflect that.

**Comment by YazzyYaz** [comment]
Sorry @sorpaas you can't change the historic title of a call just to prove your point, this isn't how it works and is just invalid. The call was about ECIP-1061 flavors, not 1072 specifically.

You also conveniently only have notes of the end of the call written 1 week after the call happened and no notes of the entire call at all. We weren't born yesterday, @sorpaas.

Changing the title back to its original state.

**Comment by sorpaas** [comment]
@YazzyYaz Well. As I mentioned, even if you use Afri's note, there will be several logic inconsistency if you argue the conclusion was ECIP-1061. It was not about 1072 specifically, of course, but it's also not about 1061 specifically, based on the content.

I don't know what's wrong with only having notes towards the end of the call, because that's usually when decisions happen. Besides, I asked a question near the end about 1072, so it's reasonable I'll take notes just from the point when I started to ask questions.

If you still have doubt that the conclusions we reached was 1072, again, as I said, look in Discord chat history to find other people who has also reached the same conclusion!

**Comment by soc1c** [comment]
Stop changing the title of this call @sorpaas.

You are overstepping your permissions as editor and abusing your rights here. I understand you have a different view on the things but you should be mindful about your push access to this repository. 

Thanks.

**Comment by sorpaas** [comment]
@soc1c What's wrong for editing the title for more accurate information? I have not been removing anything you wrote after all!

The call was indeed about both 1061 and 1072. Maybe removing both from the title will satisfy you?

**Comment by soc1c** [comment]
Ok, that works. But please be more mindful about these changes in future.

**Comment by drd34d** [comment]
Calm down Yaz. You can keep trying to silence community members who you disagree with but you won't succeed.

**Comment by YazzyYaz** [comment]
@drd34d ok boomer
