### ISSUE TITLE
ECIP-1000: Hidden Censorhip

### ISSUE THREAD

**Issue by drd34d** [ethereumclassic/ECIPs#243]
**Issue:** 
The creator of an issue or PR can, **unknowingly to other owners**, censor comments and other actions from any user he wishes by blocking the user from his personal account. This will block the user from participating in his PRs or issues.

**Why:**
This is in direct violation of ECIP-1000:

> Will ECIP comments be censored or limited to particular participants/"experts"?
> 
> Participants should freely refrain from commenting outside of their area of knowledge or expertise. However, comments should not be censored, and participation should be open to the public.

**Proof:**
Example, this is how I see the "Code of Conduct" PR (how ironic..) where I'm unable to comment.

![image](https://user-images.githubusercontent.com/30156189/70189390-1c87aa00-16eb-11ea-9978-a7144a71d5ca.png)

And before someone comes up with a crazy story like "deleted the repo owners by accident", this is also not an accidental consequence of a personal feud or whatever one might call it. This is very clear and likely the only reason for such block, as per githubs description prior to blocking.

![image](https://user-images.githubusercontent.com/30156189/70189783-1b0ab180-16ec-11ea-8dab-3475ed29efe5.png)

At this point I feel there's a 50/50 chance that I will get banned from this github organization as a whole for voicing abuses but I can assure you, once again, I will not be easily censored. All it takes is another github account.

@bobsummerwill you weirdly messaged me the other day, saying you "run the show" in ETC
Coop

Is this how you show it? 
Note taken.

**Comment by bobsummerwill** [comment]
I have no rights in this repository, @drd34d.
I guess that @YazzyYaz has blocked you in Github?

I don't know if there is a systemic way for us to disallow blocking within the context of this repository, or whether blocked users simply cannot comment on any issue anywhere in any repo which were created by the person who created them?

**Comment by YazzyYaz** [comment]
@drd34d I only blocked you because I didn't want to receive github notifications from you specifically given your vulgarity on Twitter where you're also blocked.

However, I promise you I didn't intend for you not to speak on an issue I created in Github (I assumed blocking doesn't do much on Github other than to minimize notifications from the person).

With that said, I will unblock you here.

**Comment by drd34d** [comment]
Your intention is obvious, the Github warning and description is very clear about the consequences, as shown in the image above. 

Saying it was unintended is like saying you deleted all the repo owners by accident, something that one of your employers is famous for, thus I conclude you're just another Krykoder. 

History is written and you've made clear where you stand.

**Comment by YazzyYaz** [comment]
@drd34d i blocked you on Github ages ago, I apologize if I forgot what blocking entailed back then when I created this new ECIP. As you can see, you're not very high on my list of considerations when I do my work, contrary to your belief.

Comparing me to Krykoder is hysterical. I'm only employed by the Cooperative. 

I frankly don't care to convince you about my intentions, it was simply an accident. Accept this explanation or not, I really don't care, since as I said before, you're not very important to me. However, I don't want to censor anyone accidentally on Github ECIP repo, which is why I unblocked you.

Gabish?

**Comment by drd34d** [comment]
Calm down, I get it, we get it, I'm not important to you.
