### ISSUE TITLE
Proposal for owner, member, editor, & author removal

### ISSUE THREAD

**Issue by TokenHash** [ethereumclassic/ECIPs#273]
This is the discussion page for the proposal to remove Wei Tang from internal functions in this ETC repo.

**Comment by drd34d** [comment]
what's the rationale for said proposal?

**Comment by TokenHash** [comment]
It's on the text of the ECIP proposal.

**Comment by sorpaas** [comment]
I agree with this. As maintainer of one of the three major clients for ETC, multi-geth, author of the current ECIP-1000 process, and many specifications currently active on the ETC network, if what I'm doing is not appreciated, I'll be happy to leave the ETC community.

I guess this issue is related to ECIP-1061. Back in the beginning of the discussion, I have been objecting ECIP-1061 because it has not followed the process (#220). I specifically said, in the [discussion thread](https://github.com/ethereumclassic/ECIPs/pull/220#issuecomment-561401805), that this may result in security flaws:

> I don't know what you want to accomplish here by arguing a thing that's not even related to this PR -- we're talking about violation of ECIP-1061, and it's not even related to the discussion of ECIP-1061 vs ECIP-1072. I can only take this as you're so confident in the ECIP you're proposing that you think there's absolutely no issue in the specification or whatsoever.

ETC Cooperative and Afri, however, tried really hard to silence that objection, and continued to push forward ECIP-1061, which I think it's totally inappropriate. Later, we indeed discovered design, and possibly security issues within the specification (https://corepaper.org/ethereum/fork/istanbul/#_ethereum_classic). ETC Cooperative, however, continue to try to use the argument of "doxxing" and "personal attacks" (https://github.com/ethereumclassic/ECIPs/pull/267) to try to cover up their wrongdoings on ECIP-1061, and goes as far as trying to remove me from the ETC community.

I work on Polkadot and Substrate and really don't have any financial gains in ETC. If this continues, I think I can only say farewell. So long and thanks for all the fish!

**Comment by TokenHash** [comment]
As the person being in the process of proposed removal agrees with his removal as can be seen above: https://github.com/ethereumclassic/ECIPs/issues/273#issuecomment-576400325

Which is the same effect as presenting his resignation, I propose other editors and repo managers to proceed to remove @sorpaas ASAP.

**Comment by drd34d** [comment]
This social attack serves the ETC Cooperatives agenda like a glove. I wonder why are you being a sock puppet for ETC Coop @TokenHash ? Are you still looking for that 200k funding to write articles about ETC?

@sorpaas has been a VERY VALUABLE contributor for many years, even before you two were around. A clear example is that he disclosed specification issues with the ECIP-1061 that was rushed and controversial by @bobsummerwill and his employees.

@sorpaas do not fall into this trap, it's been obvious that having you around is an obstacle for ETC Coop's agenda but you're definatelly very appreciated in this community.

**Comment by bobsummerwill** [comment]
Superceded by #276 now, isn't it, @TokenHash?

**Comment by TokenHash** [comment]
Yes. Closing as this was superseded by https://github.com/ethereumclassic/ECIPs/issues/276
