### ISSUE TITLE
ECIP-1098 proto-Treasury system for ETC

### ISSUE THREAD

**Issue by bpmckenna** [ethereumclassic/ECIPs#350]
The issue is the discussion for ethereumclassic#349 which proposes a Proto Treasury for ETC

**Comment by phyro** [comment]
Thanks for writing the proposal. I have a few questions regarding
> - 20% goes to the p-ECTS smart contract address or the burn address (0x0)

I'd first like to explain why I think that sending to the burn address in this case may be very different than a user sending to the burn address. If I have 10 ETC and decide to send it to `0x0` then that's fine because it is as if I mistakenly sent the coins to an address that doesn't have an owner and never will have one (unless someone breaks the discrete log, but we can assume this won't happen). In this case, the coins existed and had an owner that sent them to void. The situation is very different if the miners decide to send 20% of the reward to `0x0`, because the coins **never had an owner and never will**. I think this is the same as the coins never existing. Yes, I'm hinting that it could be (and suspect it is) a change to the Monetary policy. A counter argument could be "well, you can see the coins on the chain, they're there and you can count them", but the important difference which makes them the same as the ones that don't exist is that they can't ever have an owner. Coins that are not on the chain and don't exist have exactly the same usage properties as the coins burned by the miners. The miners never _send_ them to `0x0`. They can't _send_ because they never own them, they only decide whether the coins will exist in the treasury contract or they won't exist at all.

Right now, I'm of the opinion that this changes the Monetary policy. If we treat these coins as never existing, does this change the miner incentives regarding their treasury decision?

**Comment by ntallar** [comment]
>The miners never send them to 0x0

Wouldn't the same argument apply for the case that the 20% is sent to the proto-treasury contract? We think this is just a matter of how you're viewing what's happening with the block reward, if you see the miners as selecting were the 20% of the emission would go to (as they do as well with the other 80% with the coinbase address) you remove that impossible event happening of sending the coins without owner.

>Coins that are not on the chain and don't exist have exactly the same usage properties as the coins burned by the miners

We agree with this! And tbh we only see a (maybe minor?) difference between burning the 20% or never emitting them in the first place, in terms of users/miners effect we don't see anything that would change if you go one way or the other.

The only difference we see for now is that as the total number of coins emmitted will be different, which:
- if the 20% are never emitted, the total supply will be closer to what it really is
- but calculations (and so estimations) of total supply will be more difficult, which might affect this pending question _"Obtaining the exact total supply from a smart contract is not easy, and we'll probably need to make some estimations, like taking the average of a lower and upper bound."_
