### ISSUE TITLE
ECIP-1058: On-chain registry of official media resources

### ISSUE THREAD

**Issue by Dexaran** [ethereumclassic/ECIPs#64]
< Placeholder >

**Comment by soc1c** [comment]
Hi, 1056 is Agharta. What about 1058?

ref https://github.com/etclabscore/ECIPs/pull/13

ref https://github.com/ethereumclassic/ECIPs/pull/61

**Comment by saturn-network** [comment]
A [TCR](https://blog.saturn.network/what-is-a-token-curated-registry-tcr/) for official media and social resources would be a great idea.

Pros:

* Motivated stakeholders can curate the list, instead of a single party who owns reddit / website
* Ability to coordinate and vote out toxic channels (like CowOperate's eth_classic telegram)
* Drives more dapp usage and encourages people to learn how to install wallets & use ETC and tokens, instead of holding ETC on binance and using it for speculation only

Cons:

* Requires a token (which isn't a bad thing) that is _fairly distributed among motivated participants_ (which is a hard thing to solve). Airdropping the token to everyone who holds ETC is not a good idea, but how do you select whom to airdrop? If there are good proposals on how to solve this issue then it's not worth even trying.

Perhaps distributing an equal amount of tokens among ECIP participants could be a good start + some mechanism to distribute tokens to individuals who want to join (e.g. a faucet, bounty campaigns that encourage contributions to ETC code and ETC community work).

Successful TCR examples:

* [TCRParty](https://www.tcr.party/)
* [DIRT protocol / openmarketcap](https://dev.dirtprotocol.com/)

**Comment by bobsummerwill** [comment]
There is no actual proposal here.  Please can we close this?
